---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: O Cloud Volumes ONTAP 9.13.1 inclui uma nova melhoria. 
---
= Novidades do Cloud Volumes ONTAP 9.13.1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O Cloud Volumes ONTAP 9.13.1 inclui novos aprimoramentos.

Recursos e aprimoramentos adicionais também são introduzidos nas versões mais recentes do BlueXP . Consulte https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["Notas de versão do BlueXP"^] para obter detalhes.



== 9.13.1 P12 (25 de novembro de 2024)

O patch 9.13.1 P12 já está disponível para o Cloud Volumes ONTAP para todos os provedores de nuvem. O BlueXP  solicitará que você atualize seus sistemas existentes para esta versão de patch.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P12["Veja a lista de bugs corrigidos no patch P12"^] (É necessário iniciar sessão no site de suporte da NetApp).



== 9.13.1 P11 (14 de outubro de 2024)

O patch 9.13.1 P11 já está disponível para o Cloud Volumes ONTAP para todos os provedores de nuvem. O BlueXP  solicitará que você atualize seus sistemas existentes para esta versão de patch.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P11["Veja a lista de bugs corrigidos no patch P11"^] (É necessário iniciar sessão no site de suporte da NetApp).



== 9.13.1 P10 (8 de agosto de 2024)

O patch 9.13.1 P10 já está disponível para o Cloud Volumes ONTAP para todos os provedores de nuvem. O BlueXP  solicitará que você atualize seus sistemas existentes para esta versão de patch.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P10["Veja a lista de bugs corrigidos no patch P10"^] (É necessário iniciar sessão no site de suporte da NetApp).



== 9.13.1 P9 (22 de maio de 2024)

O patch 9.13.1 P9 já está disponível para o Cloud Volumes ONTAP para todos os provedores de nuvem. O BlueXP  solicitará que você atualize seus sistemas existentes para esta versão de patch.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P9["Veja a lista de bugs corrigidos no patch P9"^] (É necessário iniciar sessão no site de suporte da NetApp).



== 9.13.1 P8 (18 de abril de 2024)

O patch 9.13.1 P8 já está disponível para o Cloud Volumes ONTAP para todos os provedores de nuvem. O BlueXP  solicitará que você atualize seus sistemas existentes para esta versão de patch.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P8["Veja a lista de bugs corrigidos no patch P8"^] (É necessário iniciar sessão no site de suporte da NetApp).



== 9.13.1 P7 (1 de abril de 2024)

O patch 9.13.1 P7 já está disponível para o Cloud Volumes ONTAP para todos os provedores de nuvem. O BlueXP  solicitará que você atualize seus sistemas existentes para esta versão de patch.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P7["Veja a lista de bugs corrigidos no patch P7"^] (É necessário iniciar sessão no site de suporte da NetApp).



== 9.13.1 P6 (5 de fevereiro de 2024)

O patch 9.13.1 P6 já está disponível para o Cloud Volumes ONTAP para todos os provedores de nuvem. O BlueXP  solicitará que você atualize seus sistemas existentes para esta versão de patch.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P6["Veja a lista de bugs corrigidos no patch P6"^] (É necessário iniciar sessão no site de suporte da NetApp).



== 9.13.1 P4 (8 de dezembro de 2023)

O patch 9.13.1 P4 já está disponível para o Cloud Volumes ONTAP para todos os provedores de nuvem. O BlueXP  solicitará que você atualize seus sistemas existentes para esta versão de patch.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P4["Veja a lista de bugs corrigidos no patch P4"^] (É necessário iniciar sessão no site de suporte da NetApp).



== 9.13.1 P2 e 9.13.1 P3 (20 de Outubro de 2023)

Os patches 9.13.1 P2 e 9.13.1 P3 agora estão disponíveis para Cloud Volumes ONTAP para todos os provedores de nuvem se você tiver um conetor executando a versão 3.9.26 ou posterior. O BlueXP  solicitará que você atualize seus sistemas existentes para esta versão de patch.

* link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P3["Veja a lista de bugs corrigidos no patch P3"^] (É necessário iniciar sessão no site de suporte da NetApp).
* link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P2["Veja a lista de bugs corrigidos no patch P2"^] (É necessário iniciar sessão no site de suporte da NetApp).




== 9.13.1 P1 (3 de outubro de 2023)

O patch 9.13.1 P1 agora está disponível para o Cloud Volumes ONTAP para todos os provedores de nuvem se você tiver um conetor executando a versão 3.9.26 ou posterior. O BlueXP  solicitará que você atualize seus sistemas existentes para esta versão de patch.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P1["Veja a lista de bugs corrigidos no patch P1"^] (É necessário iniciar sessão no site de suporte da NetApp).



== 9.13.1 GA (26 de Julho de 2023)

A versão de disponibilidade geral do Cloud Volumes ONTAP 9.13.1 já está disponível na AWS, Azure e Google Cloud.



== 9.13.1 RC1 (26 de junho de 2023)

O Release Candidate 1 do Cloud Volumes ONTAP 9.13.1 já está disponível na AWS, Azure e Google Cloud.

Algumas melhorias no desempenho do FabricPool podem afetar seus dados em camadas no Cloud Volumes ONTAP.

.Melhorias na velocidade de leitura sequencial e na disposição em camadas
Devido à performance de leitura aprimorada e à taxa de transferência em camadas no FabricPool, é possível que haja uma taxa mais alta de `GET` operações e `PUT` armazenamentos de objetos no local. Certifique-se de que existe espaço suficiente para um desempenho perfeito.

Para saber mais, consulte a. https://www.netapp.com/media/17239-tr-4598.pdf["Guia de práticas recomendadas da FabricPool"^]

.Funcionalidade Readahead agressiva
O `Aggressive Readahead` recurso no FabricPool pode aumentar as operações de leitura em um nível de arquivo, o que, por sua vez, pode aumentar os custos de leitura e a utilização de memória na nuvem pública.

Para saber mais, consulte a documentação do ONTAP: https://docs.netapp.com/us-en/ontap/fabricpool/enable-disable-aggressive-read-ahead-task.html#enable-aggressive-read-ahead-mode-during-volume-creation["Ativar e desativar o modo de leitura antecipada agressivo"^]

.Funcionalidade Cloud Write
Esse recurso permite que os clientes NFS gravem diretamente no nível de capacidade no FabricPool. Este recurso tem certas limitações e deve ser usado com cuidado. Por exemplo, se o tráfego NFS de gravação na nuvem for adicionado ao tráfego ONTAP normal, como o SnapMirror, o objetivo geral do ponto de restauração (RPO) e o objetivo de tempo de recuperação (rto) no SnapMirror poderão ser afetados.

Para saber mais, consulte a documentação do ONTAP: https://docs.netapp.com/us-en/ontap/fabricpool/enable-disable-volume-cloud-write-task.html["Ative e desative volumes para gravação diretamente na nuvem"^]



== Notas de atualização

Leia estas notas para saber mais sobre a atualização para esta versão.



=== Como atualizar

As atualizações do Cloud Volumes ONTAP devem ser concluídas a partir do BlueXP . Você não deve atualizar o Cloud Volumes ONTAP usando o Gerenciador de sistema ou a CLI. Isso pode afetar a estabilidade do sistema.

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["Saiba como atualizar quando o BlueXP  o notificar"^].



=== Caminho de atualização suportado

Você pode atualizar para o Cloud Volumes ONTAP 9.13.1 a partir das versões 9.12.1 e 9.13.0. A BlueXP  solicitará que você atualize os sistemas Cloud Volumes ONTAP qualificados para esta versão.



=== Versão necessária do conetor

O conetor BlueXP  deve estar executando a versão 3.9.26 ou posterior para implantar novos sistemas Cloud Volumes ONTAP 9.13.1 e atualizar os sistemas existentes para o 9.13.1.


TIP: As atualizações automáticas do conetor são ativadas por padrão, portanto, você deve estar executando a versão mais recente.



=== Tempo de inatividade

* A atualização de um sistema de nó único leva o sistema off-line por até 25 minutos, durante os quais a e/S é interrompida.
* A atualização de um par de HA não causa interrupções e e/S é ininterrupta. Durante esse processo de atualização sem interrupções, cada nó é atualizado em conjunto para continuar fornecendo e/S aos clientes.




=== as instâncias c4, m4 e r4 não são mais compatíveis

Na AWS, os tipos de instância C4, M4 e R4 EC2 não são mais compatíveis com o Cloud Volumes ONTAP. Se você tiver um sistema existente que esteja sendo executado em um tipo de instância C4, M4 ou R4, será necessário alterar para um tipo de instância na família de instâncias C5, M5 ou R5. Não é possível atualizar para esta versão até alterar o tipo de instância.

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html["Saiba como alterar o tipo de instância EC2 para Cloud Volumes ONTAP"^].

link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["Suporte à NetApp"^]Consulte para saber mais sobre o fim da disponibilidade e suporte para esses tipos de instância.
